# SPDX-FileCopyrightText: 2025 Aaron White <w531t4@gmail.com>
# SPDX-License-Identifier: MIT
FROM mcr.microsoft.com/vscode/devcontainers/base:bookworm

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN \
    apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        git \
        cmake \
        autoconf \
        libreadline-dev \
        libcairo2 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src

COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

USER vscode

ENV VIRTUAL_ENV="/home/vscode/.local/venv"
RUN --mount=type=bind,source=.python-version,target=.python-version \
    uv python install \
    && uv venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

# Install Python dependencies from requirements
RUN --mount=type=bind,source=.python-requirements,target=.python-requirements \
    uv pip install -r .python-requirements

ENV ESPHOME_DATA_DIR=/home/vscode/.cache/.esphome
RUN --mount=type=bind,source=minimal_esphome.yaml,target=minimal_esphome.yaml \
    --mount=type=bind,source=components,target=components \
    --mount=type=bind,source=.gitignore,target=.gitignore \
    python3 -m esphome compile minimal_esphome.yaml

WORKDIR /workspaces

# Set the default shell to bash instead of sh
ENV SHELL=/bin/bash
