#!/bin/sh
# SPDX-FileCopyrightText: 2025 Aaron White <w531t4@gmail.com>
# SPDX-License-Identifier: MIT
# Stop on errors
set -e

cd "$(realpath "$(dirname "$0")/..")"

echo "Installing development dependencies..."

# Install esphome
uv pip install \
  -r .python-requirements \
  colorlog \
  --upgrade \
  --config-settings editable_mode=compat

# Fix issue where clang-format looks in
# /home/vscode/.cache/.esphome/build/clangd/src/esphome/components/display_layout/
ln -sf /workspaces/ESPHome-display_layout/.clang-format /home/vscode/.clang-format
ln -sf /workspaces/ESPHome-display_layout/.clangd /home/vscode/.clangd

.devcontainer/bootstrap-private-configs
