#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2025 Aaron White <w531t4@gmail.com>
# SPDX-License-Identifier: MIT

# Stop on errors
set -e

cd "$(dirname "$0")/.."

# Add default vscode settings if not existing
SETTINGS_FILE=./.vscode/settings.json
# SETTINGS_TEMPLATE_FILE=./.vscode/settings.default.jsonc
# if [ ! -f "$SETTINGS_FILE" ]; then
#     echo "Copy $SETTINGS_TEMPLATE_FILE to $SETTINGS_FILE."
#     cp "$SETTINGS_TEMPLATE_FILE" "$SETTINGS_FILE"
# fi

.devcontainer/bootstrap

pre-commit install
